<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>BitInspectorTabo</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Debug_Unpackaged;Release_Unpackaged;Release_Unpackaged_AOT;Release_AOT</Configurations>
	<Packaged>true</Packaged>
	<Packaged Condition="'$(Configuration)'=='Debug_Unpackaged' or '$(Configuration)'=='Release_Unpackaged' or '$(Configuration)'=='Release_Unpackaged_AOT'">false</Packaged>
	<Optimized>true</Optimized>
	<Optimized Condition="'$(Configuration)'=='Debug' or '$(Configuration)'=='Debug_Unpackaged'">false</Optimized>
	<PublishAot>false</PublishAot>
	<PublishAot Condition="'$(Configuration)'=='Release_AOT' or '$(Configuration)'=='Release_Unpackaged_AOT'">true</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Packaged)'=='false'">
	<WindowsPackageType>None</WindowsPackageType>
	<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	<PublishSingleFile>true</PublishSingleFile>
    <PublishDir>$(SolutionDir)bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)</PublishDir>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Packaged)'=='true'">
    <AppxBundleNameForOutput>$(MSBuildProjectName)</AppxBundleNameForOutput>
	<AppInstallerUri>$(SolutionDir)bin\$(Configuration)\$(TargetFramework)</AppInstallerUri>
	<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
	<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
	<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
	<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
	<GenerateTestArtifacts>True</GenerateTestArtifacts>
	<AppxBundle>Always</AppxBundle>
	<AppxBundlePlatforms>x86|x64|arm64</AppxBundlePlatforms>
	<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
	<PackageCertificateThumbprint>b8663973a60f06fb6e2d3ec853a0bcb2fc1d163c</PackageCertificateThumbprint>
	<AppxFilterOutUnusedLanguagesResourceFileMaps>False</AppxFilterOutUnusedLanguagesResourceFileMaps>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishAot)'=='true'">
    <PublishSingleFile>false</PublishSingleFile>
	<IsAotCompatible>true</IsAotCompatible>
	<SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
	<OptimizationPreference>speed</OptimizationPreference>
	<AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Pages\ErrorPage.xaml" />
    <None Remove="Pages\HelpPage.xaml" />
    <None Remove="Pages\InspectorPage.xaml" />
    <None Remove="Pages\MainPage.xaml" />
    <None Remove="Pages\SettingsPage.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\HelpPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\SettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\InspectorPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\ErrorPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Resources\DescriptionStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>